slug: git/t/configuration
name: Git Configuration Snippets
shortName: Configuration
parent: collection/git
languageMatcher: git
tagMatcher: configuration
description: >-
  The Git snippet collection contains a variety of short tips and tricks for all
  currently maintained versions of git. It includes most commonly-used commands
  and covers various use-cases in the form of simplified documentation, complete
  with multiple examples.
shortDescription: >-
  A snippet collection of simplified git documentation and tips, covering most
  commonly-used commands and covering various use-cases.
splash: keyboard-coffee.png
